# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build FocusApi

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore src/FocusApi/FocusApi.csproj
      - name: Build
        run: dotnet build src/FocusApi/FocusApi.csproj --configuration Release --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal